disrepency_helper = {
    "Michal Kwiatkowski": "KWIATKOWSKI Michał",
    "Gorka Izagirre Insausti": "IZAGIRRE Gorka",
    "Enric Mas Nicolau": "MAS Enric",
    "Benoit Cosnefroy": "COSNEFROY Benoît",
    "Aurelien Paret-Peintre": "PARET-PEINTRE Aurélien",
    "Rafal Majka": "MAJKA Rafał",
    "Tadej Pogacar": "POGAČAR Tadej",
    "Rigoberto Uran": "URÁN Rigoberto",
    "Ruben Antonio Almeida Guerreiro": "GUERREIRO Ruben",
    "Florian Senechal": "SÉNÉCHAL Florian",
    "Remi Cavagna": "CAVAGNA Rémi",
    "Mikkel Frølich Honore": "HONORÉ Mikkel Frølich",
    "Matej Mohoric": "MOHORIČ Matej",
    "Søren Kragh Andersen": "KRAGH ANDERSEN Søren",
    "Felix Grossschartner": "GROßSCHARTNER Felix",
    "Pierre-Luc Perichon": "PÉRICHON Pierre-Luc",
    "Ion Izagirre Insausti": "IZAGIRRE Ion",
    "Carl Fredrik Hagen": "HAGEN Carl Fredrik",
    "Mads Wurtz Schmidt": "WÜRTZ SCHMIDT Mads",
    "Primoz Roglic": "ROGLIČ Primož",
    "Matteo Jorgensen": "JORGENSON Matteo",
    "Lukasz Owsian": "OWSIAN Łukasz",
    "Mathieu Ladagnous": "LADAGNOUS Matthieu",
    "Jonathan Castroviejo Nicolas": "CASTROVIEJO Jonathan",
    "Daniel Felipe Martinez": "MARTÍNEZ Daniel Felipe",
    "Miguel Angel Lopez": "LÓPEZ Miguel Ángel",
    "Gregor Muhlberger": "MÜHLBERGER Gregor",
    "Maximilian Walscheid": "WALSCHEID Max",
    "Mikael Cherel": "CHEREL Mikaël",
    "Luis Leon Sanchez": "SÁNCHEZ Luis León",
    "Toms Skujins": "SKUJIŅŠ Toms",
    "Amund Grondahl Jensen": "JANSEN Amund Grøndahl",
    "Christopher Juul Jensen": "JUUL-JENSEN Christopher",
    "Jeremy Lecroq": "LECROQ Jérémy",
    "Luca Mozatto": "MOZZATO Luca",
    "Luca Mozato": "MOZZATO Luca",
    "Jesus Herrada Lopez": "HERRADA Jesús",
    "Remy Rochas": "ROCHAS Rémy",
    "Jose Herrada": "HERRADA José",
    "Ruben Fernandez Andujar": "FERNÁNDEZ Rubén",
    "Clement Champoussin": "CHAMPOUSSIN Clément",
    "Kamil Malecki": "MAŁECKI Kamil",
    "Carlos Rodriguez": "RODRÍGUEZ Carlos",
    "Lluis Mas Bonet": "MAS Lluís",
    "Juan Sebastian Molano": "MOLANO Juan Sebastián",
    "Sebastien Reichenbach": "REICHENBACH Sébastien",
    "Juan Pedro Lopez": "LÓPEZ Juan Pedro",
    "Elie Gesbert": "GESBERT Élie",
    "Clement Russo": "RUSSO Clément",
    "Oscar Cabedo": "CABEDO Óscar",
    "José Manuel Diaz": "DÍAZ José Manuel",
    "Jesus Ezquerra Muela": "EZQUERRA Jesús",
    "Angel Madrazo": "MADRAZO Ángel",
    "Hector Carretero Millan": "CARRETERO Héctor",
    "Raul Garcia Pierna": "GARCÍA PIERNA Raúl",
    "Jose Felix Parra": "PARRA José Félix",
    "Vojtech Repa": "ŘEPA Vojtěch",
    "Xabier Mikel Azparren": "AZPARREN Xabier Mikel",
    "Luis Angel Mate": "MATÉ Luis Ángel",
    "Mikel Iturria Segurola": "ITURRIA Mikel",
    "Gotzon Martin": "MARTÍN Gotzon",
    "Mikel Bizkarra Etxegibel": "BIZKARRA Mikel",
    "Jose Joaquin Rojas Gil": "ROJAS José Joaquín",
    "Joao Almeida": "ALMEIDA João",
    "Rein Taaramae": "TAARAMÄE Rein",
    "Tobias Halland Johannessen": "Johannessen Tobias Halland",
    "Jorge Arcas Pena": "Arcas Jorge",
    "Loic Vliegen": "Vliegen Loïc",
    "Antonio Pedrero Lopez": "Antonio Pedrero",
    "Clement Berthet": "BERTHET Clément",
    "Alexander Edmondson": "EDMONDSON Alex ",
    "Jonas Rickart": "RICKAERT Jonas",
    "Casper Phillip Pedersen": "PEDERSEN Casper",
    "Matevz Govekar": "GOVEKAR Matevž",
    "Clement Davy": "DAVY Clément",
    "Romain Gregoire": "GRÉGOIRE Romain",
    "Ivan Garcia Cortina": "GARCÍA CORTINA Iván",
    "Einer Augusto Rubio": "RUBIO Einer Augusto",
    "Pelayo Sanchez": "SÁNCHEZ Pelayo",
    "David Gonzalez": "GONZÁLEZ David",
    "Fernando Barcelo": "BARCELÓ Fernando",
    "Cristian Rodriguez Martin": "RODRÍGUEZ Cristián",
    "Kevin Ledanois": "LEDANOIS Kévin",
    "Francois Bidard": "BIDARD François",
    "Kevin Vauquelin": "VAUQUELIN Kévin",
    "Damien Touze": "TOUZÉ Damien",
    "Eduardo Sepulveda": "SEPÚLVEDA Eduardo",
    "Sebastien Grignard": "GRIGNARD Sébastien"
}
